const char* homeHtml() {
    return "HTTP/1.1 200 OK"
    "\nContent-Type: text/html"
    "\nConnection: close"
    "\n"
    "\n<!DOCTYPE HTML>"
    "\n<html>"
    "\n<head><title>Lumina Spargere</title>"
    "\n<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "\n"
    "\n<style>button{background-color:#f44336border:nonecolor:whitepadding:15px 32pxtext-align:centertext-decoration:nonedisplay:inline-blockfont-size: 24px transition-duration: 0.4s}button:hover{background-color: #4CAF50  color: white}</style>"
    "\n</head>"
    "\n<body>"
    "\n<div style='text-align:center'>"
    "\n<h1 align='center'>Lumina Spargere</h1>"
    "\n<br />"
    "\n<button onClick=location.href='./?FRENTE'>FRENTE</button><br>"
    "\n<button onClick=location.href='./?RE'>RE</button><br>"
    "\n<button onClick=location.href='./?DIREITA'>DIREITA</button><br>"
    "\n<button onClick=location.href='./?ESQUERDA'>ESQUERDA</button><br>"
    "\n<button onClick=location.href='./?PARAR'>PARAR</button>"
    "\n<br />"
    "\n</div>"
    "\n</body>"
    "\n</html>";
}